import 'dart:io';

import 'package:labwright_seq/labwright_seq.dart';

/// TestStand XML model-coverage report — the sibling of the VI coverage tool.
///
/// Walks the fetched corpus (`corpus/seq/`), and for each XML `.seq` reports how
/// much of the `Data` property tree the typed lens surfaces (`modeled/total`).
/// Prints a per-source + total table and writes a gitignored `corpus/seq/REPORT.md`
/// so the scorecard is regenerated from the live decoders, never hand-maintained.
///
/// Run: `dart run tool/coverage.dart [corpusRoot=<package>/corpus/seq]`
String _defaultCorpusRoot() {
  const pkgRel = 'packages/labwright_seq/corpus';
  var d = Directory.current;
  for (var i = 0; i < 8; i++) {
    if (File('${d.path}/$pkgRel/seq-sources.json').existsSync()) return '${d.path}/$pkgRel/seq';
    if (File('${d.path}/corpus/seq-sources.json').existsSync()) return '${d.path}/corpus/seq';
    final p = d.parent;
    if (p.path == d.path) break;
    d = p;
  }
  return 'corpus/seq';
}


class _Stat {
  int files = 0, seqs = 0, steps = 0;
  var cov = const SeqCoverage(total: 0, modeled: 0);
}

void main(List<String> args) {
  final root = args.isNotEmpty ? args[0] : _defaultCorpusRoot();
  final rootDir = Directory(root);
  if (!rootDir.existsSync()) {
    stderr.writeln('corpus not found: $root (run tool/fetch_seq_corpus.dart)');
    exit(1);
  }

  final bySource = <String, List<File>>{};
  for (final src in rootDir.listSync().whereType<Directory>()) {
    final name = src.path.split('/').last;
    for (final f in src.listSync(recursive: true).whereType<File>()) {
      if (f.path.toLowerCase().endsWith('.seq')) (bySource[name] ??= []).add(f);
    }
  }

  var nTotal = 0, nXml = 0, nIni = 0, nBinary = 0, nUnknown = 0;
  for (final f in bySource.values.expand((e) => e)) {
    nTotal++;
    switch (detectSeqFormat(f.readAsBytesSync())) {
      case SeqFormat.xml:
        nXml++;
      case SeqFormat.ini:
        nIni++;
      case SeqFormat.binary:
        nBinary++;
      case SeqFormat.unknown:
        nUnknown++;
    }
  }
  String pct(int a, int b) => b == 0 ? '0.0' : (100 * a / b).toStringAsFixed(1);
  String modelPct(SeqCoverage c) => (c.ratio * 100).toStringAsFixed(1);

  final overall = _Stat();
  final md = StringBuffer()
    ..writeln('| source | XML .seq | sequences | steps | modeled | total | model% |')
    ..writeln('|---|--:|--:|--:|--:|--:|--:|');
  stdout.writeln('source                              xml  seqs steps  modeled  total  model%');
  for (final src in bySource.keys.toList()..sort()) {
    final s = _measure(bySource[src]!, SeqFormat.xml);
    overall
      ..files += s.files
      ..seqs += s.seqs
      ..steps += s.steps
      ..cov = overall.cov + s.cov;
    stdout.writeln('${src.padRight(34).substring(0, 34)} ${s.files.toString().padLeft(4)} '
        '${s.seqs.toString().padLeft(5)} ${s.steps.toString().padLeft(5)} '
        '${s.cov.modeled.toString().padLeft(8)} ${s.cov.total.toString().padLeft(6)} '
        '${modelPct(s.cov).padLeft(6)}');
    md.writeln('| $src | ${s.files} | ${s.seqs} | ${s.steps} | ${s.cov.modeled} | '
        '${s.cov.total} | ${modelPct(s.cov)} |');
  }
  stdout.writeln('-' * 76);
  stdout.writeln('TOTAL ${overall.files} XML .seq · ${overall.seqs} sequences · ${overall.steps} steps · '
      'model coverage ${modelPct(overall.cov)}% '
      '(${overall.cov.modeled}/${overall.cov.total} property nodes)');

  final iniFiles = [for (final fs in bySource.values) ...fs];
  final ini = _measure(iniFiles, SeqFormat.ini);
  stdout.writeln('INI   ${ini.files} INI .seq · ${ini.seqs} sequences · ${ini.steps} steps · '
      'model coverage ${modelPct(ini.cov)}% '
      '(${ini.cov.modeled}/${ini.cov.total} property nodes)');

  String axis(SeqCoverage c) =>
      'accounted ${(c.accountedRatio * 100).toStringAsFixed(1)}% · '
      'modeled ${modelPct(c)}% · '
      'plumbing ${c.plumbing} · unaccounted ${c.unaccounted}';
  stdout.writeln('-' * 76);
  stdout.writeln('AXES — accounted% is the completeness goal (->100%); modeled% is '
      'the deferred-work\nbenchmark (rises as NI-internal plumbing is decoded):');
  stdout.writeln('  formatDetected%  ${pct(nTotal - nUnknown, nTotal)}  '
      '($nXml xml, $nIni ini, $nBinary binary, $nUnknown unknown of $nTotal .seq)');
  stdout.writeln('  XML   ${axis(overall.cov)}');
  stdout.writeln('  INI   ${axis(ini.cov)}');
  stdout.writeln('  binary  FRONTIER: $nBinary binary .seq, record grammar not yet decoded');

  final report = StringBuffer()
    ..writeln('# TestStand XML model — coverage report card')
    ..writeln()
    ..writeln('Auto-generated by `packages/labwright_seq/tool/coverage.dart`. '
        'Gitignored — do not hand-edit. Run the tool to refresh.')
    ..writeln()
    ..writeln('**model%** = fraction of `Data`-tree property nodes the typed lens '
        '(SeqFile/Sequence/Step/StepSettings/StepModule/SeqVariable) surfaces. '
        'The remainder is still available as the raw `SeqProperty` tree.')
    ..writeln()
    ..writeln(md.toString().trimRight())
    ..writeln()
    ..writeln('**TOTAL (XML)** ${overall.files} XML .seq · ${overall.seqs} sequences · '
        '${overall.steps} steps · model coverage '
        '${modelPct(overall.cov)}% '
        '(${overall.cov.modeled}/${overall.cov.total} property nodes).')
    ..writeln()
    ..writeln('**TOTAL (INI, legacy)** ${ini.files} INI .seq · ${ini.seqs} sequences · '
        '${ini.steps} steps · model coverage '
        '${modelPct(ini.cov)}% '
        '(${ini.cov.modeled}/${ini.cov.total} property nodes). Lower than XML '
        'because each step inlines its step-type definition (kept in `<typelist>` '
        'for XML); no per-step instance data is missing.');
  File('$root/REPORT.md').writeAsStringSync('$report\n');
  stdout.writeln('wrote $root/REPORT.md');
}

_Stat _measure(List<File> files, SeqFormat fmt) {
  final s = _Stat();
  for (final f in files..sort((a, b) => a.path.compareTo(b.path))) {
    final bytes = f.readAsBytesSync();
    if (detectSeqFormat(bytes) != fmt) continue;
    final SeqFile sf;
    try {
      sf = parseSeqFile(bytes);
    } catch (_) {
      continue;
    }
    s.files++;
    s.seqs += sf.sequences.length;
    s.steps += sf.sequences.fold(0, (a, seq) => a + seq.steps.length);
    s.cov = s.cov + measureCoverage(sf);
  }
  return s;
}
