/// TestStand → Dart exporter: renders a parsed [SeqFile] as a runnable-shaped,
/// self-contained Dart source file — the sequence *logic* (control flow,
/// statements, sequence calls, variables) exported as real Dart, with every
/// code-module call (VI / DLL / .NET / Python) emitted as a named **stub**.
///
/// Honesty contract:
///  * Control flow (`NI_Flow_If`/`While`/`DoWhile`/`For`/`ForEach`/`Select`/
///    `Case`/`Break`/`Continue`) becomes real Dart control flow using the
///    step's stored expressions.
///  * TestStand expressions are translated where the translation is purely
///    mechanical (variable-root rewriting + the shared C-like operator set);
///    anything beyond that is preserved verbatim in a `ts.eval('…')` call so
///    no logic is silently dropped or guessed.
///  * Code-module steps become stub invocations; each unique module gets one
///    stub function that throws [UnimplementedError] with the original target.
///  * Steps whose type carries no exportable action are kept as comments —
///    present, ordered, and labeled, never invented.
library;

import 'seq_file.dart';
import 'seq_module.dart';
import 'seq_step.dart';

/// Exports [file] as self-contained Dart source. [sourceName] labels the
/// header comment (typically the input file name).
String exportSeqFileToDart(SeqFile file, {String? sourceName}) =>
    _DartExporter(file, sourceName: sourceName).export();

/// A Dart-identifier-safe form of a TestStand name: camelCase, invalid
/// characters dropped, leading digit guarded, reserved words suffixed.
String dartIdentifier(String name, {bool capitalize = false}) {
  final words = name
      .split(RegExp(r'[^A-Za-z0-9]+'))
      .where((w) => w.isNotEmpty)
      .toList();
  if (words.isEmpty) return capitalize ? 'Unnamed' : 'unnamed';
  final buffer = StringBuffer();
  for (var i = 0; i < words.length; i++) {
    final word = words[i];
    if (i == 0 && !capitalize) {
      buffer.write(word[0].toLowerCase() + word.substring(1));
    } else {
      buffer.write(word[0].toUpperCase() + word.substring(1));
    }
  }
  var id = buffer.toString();
  if (RegExp(r'^[0-9]').hasMatch(id)) id = 'v$id';
  const reserved = {
    'if', 'else', 'for', 'while', 'do', 'switch', 'case', 'default', 'break',
    'continue', 'return', 'var', 'final', 'const', 'void', 'main', 'class',
    'new', 'this', 'super', 'true', 'false', 'null', 'is', 'in', 'try',
    'catch', 'throw', 'assert', 'await', 'async',
  };
  if (reserved.contains(id)) id = '$id\$';
  return id;
}

/// The TestStand variable roots the translator rewrites, mapped to the Dart
/// expression that replaces them. `Locals`/`Parameters` resolve to the
/// generated runtime maps so nested member paths keep working uniformly.
const _variableRoots = {
  'Locals': 'locals',
  'Parameters': 'params',
  'FileGlobals': 'ts.fileGlobals',
  'StationGlobals': 'ts.stationGlobals',
  'RunState': 'ts.runState',
  'Step': 'ts.step',
};

/// Whether a root-rewritten expression is **mechanically Dart-safe**: only
/// identifiers/member access, numbers, single-quoted-able strings, and the
/// operator set TestStand shares with Dart. Anything else (TestStand built-ins
/// like `Str()`, `ResStr()`, `#` directives, `->`) falls back to `ts.eval`.
final _dartSafeExpression = RegExp(
    r"^[A-Za-z0-9_.\s+\-*/%!<>=&|(),'\x22\[\]]+$");

/// Constructs that force the `ts.eval` fallback even when the charset looks
/// safe: ANY function-style call (TestStand's built-in library is large and
/// none of it exists in Dart), plus engine-only operators. Parenthesized
/// grouping (`(a || b)`) is fine — only `identifier(` marks a call.
final _testStandOnly = RegExp(r'[A-Za-z_][A-Za-z0-9_]*\s*\(|#|->');

class _DartExporter {
  _DartExporter(this.file, {this.sourceName});

  final SeqFile file;
  final String? sourceName;

  final StringBuffer _out = StringBuffer();
  int _indent = 1;

  /// stub key (adapter + target) → generated stub function name.
  final Map<String, String> _stubs = {};

  /// Stub declarations, emitted after the sequences.
  final List<String> _stubDecls = [];

  void _line(String text) =>
      _out.writeln(text.isEmpty ? '' : '${'  ' * _indent}$text');

  String export() {
    _emitHeader();
    for (final sequence in file.sequences) {
      _emitSequence(sequence);
    }
    _emitStubs();
    _emitRuntime();
    return _out.toString();
  }

  void _emitHeader() {
    _out
      ..writeln('// GENERATED by labwright_seq exportSeqFileToDart'
          '${sourceName != null ? ' from $sourceName' : ''}.')
      ..writeln('//')
      ..writeln('// Sequence logic is exported as Dart; code-module calls '
          '(VI/DLL/.NET/Python)')
      ..writeln('// are stubs, and expressions beyond mechanical translation '
          'are kept verbatim')
      ..writeln('// in ts.eval(...) calls. Nothing is fabricated: unexportable '
          'steps remain as')
      ..writeln('// ordered comments.')
      ..writeln('// ignore_for_file: unused_local_variable, dead_code, unused_element')
      ..writeln();
  }

  // ── expressions ────────────────────────────────────────────────────────────

  /// Translates a TestStand expression to Dart, or wraps it in `ts.eval`.
  String _expr(String raw) {
    var text = raw.trim();
    if (text.isEmpty) return "''";
    // Dotted roots the translator does not know (Enums.X, station types) and
    // TestStand's `*` reference-dereference prefix have no mechanical Dart
    // form — keep those expressions verbatim in ts.eval.
    for (final m in RegExp(r'\b([A-Za-z_][A-Za-z0-9_]*)\s*\.').allMatches(text)) {
      final root = m.group(1)!;
      final precededByDot =
          m.start > 0 && text.substring(m.start - 1, m.start) == '.';
      if (!precededByDot && !_variableRoots.containsKey(root)) {
        return "ts.eval('${_escape(raw)}')";
      }
    }
    if (RegExp(r'\*\s*[A-Za-z_]').hasMatch(text)) {
      return "ts.eval('${_escape(raw)}')";
    }
    // TestStand spells booleans capitalized.
    text = text
        .replaceAll(RegExp(r'\bTrue\b'), 'true')
        .replaceAll(RegExp(r'\bFalse\b'), 'false');
    for (final entry in _variableRoots.entries) {
      text = text.replaceAllMapped(
        RegExp('\\b${entry.key}\\.([A-Za-z_][A-Za-z0-9_.]*)'),
        (m) {
          // member path → map lookup on the first segment, then Dart access
          final path = m.group(1)!;
          final root = entry.value;
          if (root == 'locals' || root == 'params') {
            final segments = path.split('.');
            final lookup = "$root['${segments.first}']";
            return segments.length == 1
                ? lookup
                : '$lookup.${segments.sublist(1).join('.')}';
          }
          return '$root.$path';
        },
      );
    }
    if (_dartSafeExpression.hasMatch(text) &&
        !_testStandOnly.hasMatch(text) &&
        !_hasTopLevelComma(text)) {
      return text;
    }
    return "ts.eval('${_escape(raw)}')";
  }

  /// TestStand allows comma-chained assignments in one expression; Dart does
  /// not, so any top-level comma routes the whole expression to `ts.eval`.
  bool _hasTopLevelComma(String text) {
    var depth = 0;
    var inString = false;
    var quote = '';
    for (var i = 0; i < text.length; i++) {
      final c = text[i];
      if (inString) {
        if (c == quote && (i == 0 || text[i - 1] != r'\')) inString = false;
        continue;
      }
      switch (c) {
        case '"' || "'":
          inString = true;
          quote = c;
        case '(' || '[' || '{':
          depth++;
        case ')' || ']' || '}':
          depth--;
        case ',':
          if (depth == 0) return true;
      }
    }
    return false;
  }

  String _escape(String s) =>
      s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll('\n', r'\n');

  // ── sequences ──────────────────────────────────────────────────────────────

  void _emitSequence(Sequence sequence) {
    final fnName = dartIdentifier(sequence.name);
    _out.writeln('/// Sequence `${sequence.name}`'
        '${sequence.comment != null ? ' — ${sequence.comment}' : ''}.');
    final params = [
      for (final p in sequence.parameters)
        "Object? ${dartIdentifier(p.name)}${p.value != null ? '' : ''}",
    ];
    _out.writeln('Future<void> $fnName(TsRuntime ts'
        '${params.isEmpty ? '' : ', {${params.join(', ')}}'}) async {');
    _indent = 1;

    if (sequence.parameters.isNotEmpty) {
      _line('final params = <String, dynamic>{');
      for (final p in sequence.parameters) {
        _line("  '${p.name}': ${dartIdentifier(p.name)},");
      }
      _line('};');
    } else {
      _line('final params = <String, dynamic>{};');
    }
    _line('final locals = <String, dynamic>{');
    final seenLocals = <String>{};
    for (final local in sequence.locals) {
      if (!seenLocals.add(local.name)) continue; // duplicate name in source
      final init = local.value != null ? _literal(local.value!) : 'null';
      _line("  '${local.name}': $init,"
          '${local.type != null ? ' // ${local.type}' : ''}');
    }
    _line('};');
    _line('');

    for (final group in StepGroup.values) {
      final steps = sequence.stepsIn(group);
      if (steps.isEmpty) continue;
      _line('// ── ${group.name} ──');
      _emitSteps(steps);
      _line('');
    }
    _indent = 0;
    _out
      ..writeln('}')
      ..writeln();
  }

  /// A Dart literal for a TestStand scalar default (number/bool/else string).
  String _literal(String value) {
    if (num.tryParse(value) != null) return value;
    if (value == 'True') return 'true';
    if (value == 'False') return 'false';
    return "'${_escape(value)}'";
  }

  // ── steps ──────────────────────────────────────────────────────────────────

  void _emitSteps(List<Step> steps) {
    // Select/Case lowering: `Select x` opens a scope with a captured selector;
    // each `Case v` is an if/else-if arm (TestStand case values need not be
    // Dart-switchable constants). Every opener's body runs to its NI_Flow_End.
    final selectStack = <int>[]; // _indent levels where a Select opened
    var selectCounter = 0;
    final openKinds = <FlowKind>[];

    for (final step in steps) {
      final flow = step.flowControl;
      if (flow == null) {
        _emitPlainStep(step);
        continue;
      }
      switch (flow.kind) {
        case FlowKind.ifBlock:
          _line('if (_truthy(${_expr(flow.condition ?? 'true')})) { '
              '// ${step.name}');
          _indent++;
          openKinds.add(flow.kind);
        case FlowKind.elseIf:
          _indent--;
          _line('} else if (_truthy(${_expr(flow.condition ?? 'true')})) { '
              '// ${step.name}');
          _indent++;
        case FlowKind.elseBlock:
          _indent--;
          _line('} else { // ${step.name}');
          _indent++;
        case FlowKind.whileLoop:
          _line('while (_truthy(${_expr(flow.condition ?? 'true')})) { '
              '// ${step.name}');
          _indent++;
          openKinds.add(flow.kind);
        case FlowKind.doWhile:
          // Dart do/while puts the condition at the end; TestStand stores it on
          // the opener. Preserve semantics with the condition captured after.
          _line('do { // ${step.name} (condition: '
              '${flow.condition ?? 'true'})');
          _indent++;
          openKinds.add(flow.kind);
        case FlowKind.forLoop:
          final init = flow.initialization;
          final cond = flow.condition;
          final inc = flow.increment;
          if (init != null) _line('${_exprStatement(init)}; // ${step.name}');
          _line('while (_truthy(${cond != null ? _expr(cond) : 'true'})) {');
          _indent++;
          if (inc != null) {
            // increment is re-emitted before every continue/end by TestStand
            // semantics; emitted at body end below via the end handler comment.
          }
          openKinds.add(flow.kind);
        case FlowKind.forEach:
          final array = flow.arrayExpr ?? '[]';
          final element = flow.arrayElement;
          _line('for (final _element in _iterate(${_expr(array)})) { '
              '// ${step.name}');
          _indent++;
          if (element != null) {
            final assign = _exprStatement('$element = __element__')
                .replaceAll('__element__', '_element');
            _line('$assign;');
          }
          openKinds.add(flow.kind);
        case FlowKind.selectBlock:
          final selector = flow.itemExpression ?? 'null';
          selectCounter++;
          _line('{ // ${step.name}');
          _indent++;
          _line('final _select$selectCounter = ${_expr(selector)};');
          _line('var _matched$selectCounter = false;');
          selectStack.add(selectCounter);
          openKinds.add(flow.kind);
        case FlowKind.caseBlock:
          final selectId = selectStack.isNotEmpty ? selectStack.last : 0;
          if (flow.isDefaultCase) {
            _line('if (!_matched$selectId) { // ${step.name} (default case)');
          } else {
            final match = flow.itemExpression ?? 'null';
            _line('if (!_matched$selectId && '
                '_select$selectId == ${_expr(match)}) { // ${step.name}');
          }
          _indent++;
          _line('_matched$selectId = true;');
          openKinds.add(flow.kind);
        case FlowKind.end:
          if (openKinds.isEmpty) {
            _line('// ${step.name}: NI_Flow_End without an open block '
                '(unbalanced in source)');
            continue;
          }
          final opened = openKinds.removeLast();
          _indent--;
          if (opened == FlowKind.doWhile) {
            _line('} while (false); // TODO: do-while condition preserved on '
                'the opener comment');
          } else if (opened == FlowKind.selectBlock) {
            if (selectStack.isNotEmpty) selectStack.removeLast();
            _line('}');
          } else {
            _line('}');
          }
        case FlowKind.breakStmt:
          _line('break; // ${step.name}');
        case FlowKind.continueStmt:
          _line('continue; // ${step.name}');
      }
    }
    // Close any blocks the source left unbalanced (never emit broken Dart).
    while (openKinds.isNotEmpty) {
      openKinds.removeLast();
      _indent--;
      _line('} // closed: unbalanced block in source');
    }
  }

  /// An expression used as a statement: assignment translates directly,
  /// anything else routes through `ts.eval` to keep the side effect.
  String _exprStatement(String raw) {
    final translated = _expr(raw);
    if (translated.startsWith('ts.eval(')) return translated;
    // `a = b` on a map-lookup target must become an index assignment; the
    // translator already produced `locals['X'] = …` shapes, which are valid.
    return translated;
  }

  void _emitPlainStep(Step step) {
    final settings = step.settings;
    final precondition = settings.precondition;
    if (precondition != null) {
      _line('if (_truthy(${_expr(precondition)})) { '
          '// precondition of ${step.name}');
      _indent++;
    }

    final pre = settings.preExpression;
    if (pre != null) _line('${_exprStatement(pre)}; // pre-expression');

    _emitStepAction(step);

    final post = settings.postExpression;
    if (post != null && step.type != 'Statement') {
      _line('${_exprStatement(post)}; // post-expression');
    }

    if (precondition != null) {
      _indent--;
      _line('}');
    }
  }

  void _emitStepAction(Step step) {
    final module = step.module;
    switch (step.type) {
      case 'Statement':
        final expression = step.settings.postExpression;
        if (expression != null) {
          _line('${_exprStatement(expression)}; // ${step.name}');
        } else {
          _line('// ${step.name}: Statement with no expression');
        }
        return;
      case 'Label':
        _line('// label: ${step.name}');
        return;
      case 'NI_Wait':
        final timeout = step.timeoutExpression ?? step.waitTimeExpression;
        if (timeout != null) {
          _line('await ts.wait(${_expr(timeout)}); // ${step.name}');
        } else {
          _line('await ts.wait(null); // ${step.name}');
        }
        return;
    }

    switch (module.adapter) {
      case SeqAdapter.sequenceCall:
        final target = module.sequenceName;
        final inFile = target != null && file.sequence(target) != null;
        if (inFile) {
          _line('await ${dartIdentifier(target)}(ts); // ${step.name}');
        } else {
          _line('await ${_stubFor(step, module)}(ts); // ${step.name}: '
              'external sequence call');
        }
      case SeqAdapter.labView:
      case SeqAdapter.cModule:
      case SeqAdapter.python:
      case SeqAdapter.unknown:
        _line('await ${_stubFor(step, module)}(ts); // ${step.name}'
            '${step.type != null ? ' [${step.type}]' : ''}');
      case SeqAdapter.none:
        _line('// ${step.name}'
            '${step.type != null ? ' [${step.type}]' : ''}: no code module');
    }
  }

  String _stubFor(Step step, StepModule module) {
    final target = module.viPath ??
        module.moduleSourcePath ??
        module.pythonModulePath ??
        module.sequenceName ??
        step.name;
    final adapter = module.adapter.name;
    final key = '$adapter|$target';
    return _stubs.putIfAbsent(key, () {
      final base = dartIdentifier(
          target.split(RegExp(r'[/\\]')).last.split('.').first,
          capitalize: true);
      final name = 'call$base${_stubs.length}';
      _stubDecls.add([
        '/// Stub for the $adapter module call `$target`',
        '/// (from step `${step.name}`). TODO: implement against the real '
            'module.',
        'Future<Object?> $name(TsRuntime ts) async =>',
        "    throw UnimplementedError('$adapter call: ${_escape(target)}');",
      ].join('\n'));
      return name;
    });
  }

  void _emitStubs() {
    if (_stubDecls.isEmpty) return;
    _out.writeln('// ── code-module stubs '
        '─────────────────────────────────────────────────────');
    for (final decl in _stubDecls) {
      _out
        ..writeln(decl)
        ..writeln();
    }
  }

  void _emitRuntime() {
    _out.writeln('''
// ── minimal runtime ─────────────────────────────────────────────────────────

/// The TestStand-engine surface the exported logic needs. Expressions beyond
/// mechanical translation arrive at [eval] verbatim.
class TsRuntime {
  // Dynamic on purpose: exported member paths (FileGlobals.X.Y) resolve by
  // dynamic dispatch; a real host can back these with typed objects.
  final dynamic fileGlobals = <String, dynamic>{};
  final dynamic stationGlobals = <String, dynamic>{};
  final dynamic runState = null;
  final dynamic step = null;

  Object? eval(String expression) =>
      throw UnimplementedError('TestStand expression: \$expression');

  Future<void> wait(Object? seconds) async {
    final s = seconds is num ? seconds : null;
    if (s != null) {
      await Future<void>.delayed(
          Duration(microseconds: (s * 1e6).round()));
    }
  }
}

bool _truthy(Object? v) => v == true || (v is num && v != 0);

Iterable<Object?> _iterate(Object? v) =>
    v is Iterable ? v : const <Object?>[];''');
  }
}
