// The remote [DaqmxApi] backend: a pure-Dart gRPC client for the **NI gRPC Device
// Server** (https://github.com/ni/grpc-device, MIT-licensed). The server runs on a
// Windows/Linux host that has NI-DAQmx + the hardware; any platform — crucially
// macOS, which has no local NI-DAQmx — drives that hardware over gRPC.
//
// Same [DaqmxApi] as the FFI backend: callers can't tell local from remote. The wire
// types are generated by `package:protobuf` / `package:grpc` from the vendored protos
// (proto/, regenerate with tool/gen_proto.sh); this file only orchestrates them into
// the portable API, following the server's session model:
//   CreateTask -> Create{AI,AO}VoltageChan -> Read/WriteAnalogScalarF64 -> ClearTask.

import 'dart:async';
import 'dart:typed_data';

import 'package:fixnum/fixnum.dart' show Int64;
import 'package:grpc/grpc.dart';

import 'daqmx_api.dart';
import 'daqmx_constants.dart';
import 'generated/data_moniker.pb.dart' as dm;
import 'generated/data_moniker.pbgrpc.dart' show DataMonikerClient;
import 'generated/nidaqmx.pb.dart' as pb;
import 'generated/nidaqmx.pbgrpc.dart' show NiDAQmxClient;
import 'generated/session.pb.dart' as sess;
import 'generated/session.pbgrpc.dart' show SessionUtilitiesClient;
import 'logging.dart';
import 'streaming.dart';

/// [DaqmxApi] over the NI gRPC Device Server. Construct via `Daqmx.remote(...)`.
class GrpcDaqmxBackend implements DaqmxApi {
  GrpcDaqmxBackend({
    required this.host,
    this.port = defaultPort,
    this.secure = false,
    this.credentials,
    this.callTimeout = const Duration(seconds: 30),
    this.sideband = SidebandStrategy.inBandGrpc,
  });

  /// Wrap a caller-supplied [ClientChannel] (e.g. one with custom credentials,
  /// interceptors, or pointed at an in-process test server). [host]/[port] are kept
  /// only for diagnostics; the channel is used as-is. [close] still shuts it down.
  GrpcDaqmxBackend.fromChannel(
    ClientChannel channel, {
    this.host = '(injected)',
    this.port = defaultPort,
    this.callTimeout = const Duration(seconds: 30),
    this.sideband = SidebandStrategy.inBandGrpc,
  }) : secure = false,
       credentials = null,
       _channel = channel;

  /// NI gRPC Device Server's default listen port.
  static const int defaultPort = 31763;

  /// Host running the NI gRPC Device Server (the box with NI-DAQmx + hardware).
  final String host;

  /// Server port (defaults to [defaultPort]).
  final int port;

  /// Whether to use TLS when [credentials] is not supplied. `secure: true` uses
  /// `ChannelCredentials.secure()` (system root CAs only) — for self-signed / private
  /// CA / mTLS deployments (typical for NI servers), pass [credentials] instead.
  final bool secure;

  /// Explicit channel credentials. When non-null this wins over [secure] and is the
  /// way to supply a custom CA, client certificate (mTLS), or authority override.
  final ChannelCredentials? credentials;

  /// Per-RPC transport deadline. Bounds *every* call so a hung or half-open server
  /// surfaces as [DaqmxUnavailable] instead of hanging the caller forever. This is the
  /// gRPC transport deadline, distinct from the DAQmx per-read/write `timeout`.
  /// (Not applied to the open-ended [readStream] frame stream.)
  final Duration callTimeout;

  /// Streaming transport. Only [SidebandStrategy.inBandGrpc] is implemented; the
  /// faster sideband transports throw from [readStream] (see [readStream]).
  final SidebandStrategy sideband;

  ClientChannel? _channel;
  NiDAQmxClient? _daqmx;
  SessionUtilitiesClient? _utilities;
  bool _closed = false;
  int _warnedInsecure = 0;

  ClientChannel get _chan => _channel ??= () {
    final creds = credentials ?? (secure ? const ChannelCredentials.secure() : const ChannelCredentials.insecure());
    if (credentials == null && !secure && _warnedInsecure++ == 0) {
      DaqLoggers.grpc.warning(
        'connecting to $host:$port over an INSECURE (cleartext) channel; '
        'anyone on-path can read or inject DAQ commands. Use secure: true or '
        'pass credentials for anything beyond a trusted, isolated network.',
      );
    }
    DaqLoggers.grpc.fine('opening channel to $host:$port');
    return ClientChannel(
      host,
      port: port,
      options: ChannelOptions(credentials: creds),
    );
  }();

  NiDAQmxClient get _ni => _daqmx ??= NiDAQmxClient(_chan);
  SessionUtilitiesClient get _util => _utilities ??= SessionUtilitiesClient(_chan);

  CallOptions get _opts => CallOptions(timeout: callTimeout);

  void _ensureOpen() {
    if (_closed) throw StateError('GrpcDaqmxBackend used after close().');
  }

  /// Translate a transport-level gRPC failure (unreachable, hung past [callTimeout],
  /// errored) into [DaqmxUnavailable] so callers handle it like the FFI "no runtime"
  /// case. DAQmx-status failures ([DaqmxException]) pass straight through.
  Future<T> _transport<T>(String op, Future<T> Function() body) async {
    _ensureOpen();
    try {
      return await body();
    } on GrpcError catch (e) {
      DaqLoggers.grpc.warning('$op transport error: ${e.codeName} ${e.message}');
      throw DaqmxUnavailable('NI gRPC Device Server at $host:$port failed $op: ${e.codeName} ${e.message ?? ''}');
    }
  }

  /// Throw [DaqmxException] (enriched with the server's error string) when a DAQmx
  /// call comes back with a negative status; log positive warnings and pass through.
  Future<int> _check(int status, String op) async {
    if (status > 0) {
      DaqLoggers.grpc.warning('$op -> warning status $status');
      return status;
    }
    if (status == 0) return 0;
    String text;
    try {
      final r = await _ni.getErrorString(pb.GetErrorStringRequest(errorCode: status), options: _opts);
      text = r.errorString.isEmpty ? 'DAQmx status $status' : _clip(r.errorString);
    } on GrpcError {
      text = 'DAQmx status $status (error text unavailable)';
    }
    DaqLoggers.grpc.warning('$op -> status $status: $text');
    throw DaqmxException(status, text, operation: op);
  }

  /// Cap untrusted server-supplied error text so a hostile/buggy server can't flood
  /// logs or exception messages.
  static String _clip(String s) => s.length <= 1024 ? s : '${s.substring(0, 1024)}…';

  @override
  Future<List<String>> deviceNames() => _transport('EnumerateDevices', () async {
    final resp = await _util.enumerateDevices(sess.EnumerateDevicesRequest(), options: _opts);
    final names = resp.devices.map((d) => d.name).where((n) => n.isNotEmpty).toList();
    DaqLoggers.grpc.fine('EnumerateDevices -> $names');
    return names;
  });

  @override
  Future<double> readVoltage(
    String physicalChannel, {
    double min = -10,
    double max = 10,
    int terminalConfig = DaqmxVal.cfgDefault,
    double timeout = 10,
  }) => _transport('readVoltage', () async {
    final task = await _createTask();
    try {
      await _check(
        (await _ni.createAIVoltageChan(
          pb.CreateAIVoltageChanRequest(
            task: task,
            physicalChannel: physicalChannel,
            terminalConfigRaw: terminalConfig,
            minVal: min,
            maxVal: max,
            unitsRaw: DaqmxVal.volts,
          ),
          options: _opts,
        )).status,
        'DAQmxCreateAIVoltageChan',
      );
      final r = await _ni.readAnalogScalarF64(
        pb.ReadAnalogScalarF64Request(task: task, timeout: timeout),
        options: _opts,
      );
      await _check(r.status, 'DAQmxReadAnalogScalarF64');
      DaqLoggers.io.fine('readVoltage($physicalChannel) -> ${r.value}');
      return r.value;
    } finally {
      await _clearTask(task);
    }
  });

  @override
  Future<void> writeVoltage(
    String physicalChannel,
    double volts, {
    double min = -10,
    double max = 10,
    double timeout = 10,
  }) => _transport('writeVoltage', () async {
    final task = await _createTask();
    try {
      await _check(
        (await _ni.createAOVoltageChan(
          pb.CreateAOVoltageChanRequest(
            task: task,
            physicalChannel: physicalChannel,
            minVal: min,
            maxVal: max,
            unitsRaw: DaqmxVal.volts,
          ),
          options: _opts,
        )).status,
        'DAQmxCreateAOVoltageChan',
      );
      await _check(
        (await _ni.writeAnalogScalarF64(
          pb.WriteAnalogScalarF64Request(
            task: task,
            autoStart: true,
            timeout: timeout,
            value: volts,
          ),
          options: _opts,
        )).status,
        'DAQmxWriteAnalogScalarF64',
      );
      DaqLoggers.io.fine('writeVoltage($physicalChannel, $volts)');
    } finally {
      await _clearTask(task);
    }
  });

  /// Best-effort: the NI gRPC service exposes no `GetExtendedErrorInfo` RPC and no
  /// per-connection "last error" channel, so — unlike the FFI backend — this cannot
  /// report the most recent failure after the fact. Error text is delivered inline on
  /// each [DaqmxException] instead (via GetErrorString). Returns '' when healthy.
  @override
  Future<String> errorInfo() => _transport('GetErrorString', () async {
    final r = await _ni.getErrorString(pb.GetErrorStringRequest(errorCode: 0), options: _opts);
    return r.errorString;
  });

  @override
  Stream<TypedData> readStream(
    String physicalChannel, {
    required double rateHz,
    int samplesPerChunk = 1000,
    int? totalSamples,
    DaqSampleFormat format = DaqSampleFormat.volts,
    double min = -10,
    double max = 10,
    int terminalConfig = DaqmxVal.cfgDefault,
    // Ignored here: [_beginRead] issues the server-side read with an indefinite DAQmx
    // timeout, and cancelling closes the frame stream rather than waiting on a read.
    double readTimeout = 10,
  }) {
    _ensureOpen();
    if (sideband != SidebandStrategy.inBandGrpc) {
      throw UnsupportedError(
        'sideband ${sideband.name} streaming needs a native transport; only '
        'SidebandStrategy.inBandGrpc (DataMoniker.StreamRead) is implemented. '
        'See README "Streaming".',
      );
    }

    late StreamController<TypedData> controller;
    sess.Session? task;
    ResponseStream<dm.MonikerReadResponse>? frames;
    var cleaned = false;

    Future<void> cleanup() async {
      if (cleaned) return;
      cleaned = true;
      try {
        await frames?.cancel();
      } catch (_) {}
      final t = task;
      task = null;
      if (t != null) {
        try {
          await _ni.stopTask(pb.StopTaskRequest(task: t), options: _opts);
        } catch (_) {}
        await _clearTask(t);
      }
    }

    Future<void> run() async {
      task = await _createTask();
      await _check(
        (await _ni.createAIVoltageChan(
          pb.CreateAIVoltageChanRequest(
            task: task,
            physicalChannel: physicalChannel,
            terminalConfigRaw: terminalConfig,
            minVal: min,
            maxVal: max,
            unitsRaw: DaqmxVal.volts,
          ),
          options: _opts,
        )).status,
        'DAQmxCreateAIVoltageChan',
      );
      final mode = totalSamples == null ? DaqmxVal.contSamps : DaqmxVal.finiteSamps;
      await _check(
        (await _ni.cfgSampClkTiming(
          pb.CfgSampClkTimingRequest(
            task: task,
            source: '',
            rate: rateHz,
            activeEdgeRaw: DaqmxVal.rising,
            sampleModeRaw: mode,
            sampsPerChan: Int64(totalSamples ?? samplesPerChunk),
          ),
          options: _opts,
        )).status,
        'DAQmxCfgSampClkTiming',
      );
      await _check((await _ni.startTask(pb.StartTaskRequest(task: task), options: _opts)).status, 'DAQmxStartTask');

      final moniker = await _beginRead(format, task!, samplesPerChunk);
      DaqLoggers.grpc.fine('streaming via moniker "${moniker.dataSource}"');
      // No call deadline on the open-ended frame stream.
      frames = DataMonikerClient(_chan).streamRead(dm.MonikerList(readMonikers: [moniker]));

      var delivered = 0;
      await for (final frame in frames!) {
        final chunk = _decodeFrame(frame, format);
        final count = (chunk as List).length; // typed lists are List<num>
        if (count == 0) continue;
        controller.add(chunk);
        delivered += count;
        if (totalSamples != null && delivered >= totalSamples) break;
      }
    }

    controller = StreamController<TypedData>(
      onListen: () {
        run()
            .then((_) async {
              await cleanup();
              if (!controller.isClosed) await controller.close();
            })
            .catchError((Object e) async {
              await cleanup();
              if (!controller.isClosed) {
                controller.addError(
                  e is GrpcError ? DaqmxUnavailable('stream transport error: ${e.codeName} ${e.message ?? ''}') : e,
                );
                await controller.close();
              }
            });
      },
      onCancel: cleanup,
    );
    return controller.stream;
  }

  /// Begin a streaming read for [format] and return its data moniker.
  Future<dm.Moniker> _beginRead(DaqSampleFormat format, sess.Session task, int chunk) async {
    switch (format) {
      case DaqSampleFormat.volts:
        final r = await _ni.beginReadAnalogF64(
          pb.BeginReadAnalogF64Request(
            task: task,
            numSampsPerChan: chunk,
            timeout: -1,
            fillModeRaw: DaqmxVal.groupByChannel,
            arraySizeInSamps: chunk,
          ),
          options: _opts,
        );
        await _check(r.status, 'BeginReadAnalogF64');
        return r.moniker;
      case DaqSampleFormat.rawI16:
        final r = await _ni.beginReadBinaryI16(
          pb.BeginReadBinaryI16Request(
            task: task,
            numSampsPerChan: chunk,
            timeout: -1,
            fillModeRaw: DaqmxVal.groupByChannel,
            arraySizeInSamps: chunk,
          ),
          options: _opts,
        );
        await _check(r.status, 'BeginReadBinaryI16');
        return r.moniker;
      case DaqSampleFormat.rawI32:
        final r = await _ni.beginReadBinaryI32(
          pb.BeginReadBinaryI32Request(
            task: task,
            numSampsPerChan: chunk,
            timeout: -1,
            fillModeRaw: DaqmxVal.groupByChannel,
            arraySizeInSamps: chunk,
          ),
          options: _opts,
        );
        await _check(r.status, 'BeginReadBinaryI32');
        return r.moniker;
      case DaqSampleFormat.rawU16:
      case DaqSampleFormat.rawU32:
        throw UnsupportedError('gRPC streaming supports volts/rawI16/rawI32; $format uses the local FFI path.');
    }
  }

  /// Unpack one stream frame's Any payload into the format's typed list.
  TypedData _decodeFrame(dm.MonikerReadResponse frame, DaqSampleFormat format) {
    if (frame.data.values.isEmpty) return Float64List(0);
    final any = frame.data.values.first;
    switch (format) {
      case DaqSampleFormat.volts:
        final m = pb.MonikerReadAnalogF64Response();
        any.unpackInto(m);
        return Float64List.fromList(m.readArray);
      case DaqSampleFormat.rawI16:
        final m = pb.MonikerReadBinaryI16Response();
        any.unpackInto(m);
        return Int16List.fromList(m.readArray);
      case DaqSampleFormat.rawI32:
        final m = pb.MonikerReadBinaryI32Response();
        any.unpackInto(m);
        return Int32List.fromList(m.readArray);
      case DaqSampleFormat.rawU16:
      case DaqSampleFormat.rawU32:
        throw UnsupportedError('unreachable: $format rejected in _beginRead');
    }
  }

  /// Create a task with an empty session name so the server assigns a unique one —
  /// no client-side name collisions even under concurrency.
  Future<sess.Session> _createTask() async {
    final r = await _ni.createTask(pb.CreateTaskRequest(sessionName: ''), options: _opts);
    await _check(r.status, 'DAQmxCreateTask');
    DaqLoggers.task.fine('CreateTask -> "${r.task.name}"');
    return r.task;
  }

  Future<void> _clearTask(sess.Session task) async {
    try {
      final r = await _ni.clearTask(pb.ClearTaskRequest(task: task), options: _opts);
      if (r.status < 0) {
        DaqLoggers.task.warning('ClearTask("${task.name}") -> status ${r.status}');
      } else {
        DaqLoggers.task.fine('ClearTask("${task.name}")');
      }
    } on GrpcError catch (e) {
      // Best-effort cleanup: a clear failure must not mask the original outcome.
      DaqLoggers.task.warning('ClearTask("${task.name}") failed: ${e.codeName}');
    }
  }

  @override
  Future<void> close() async {
    _closed = true;
    final ch = _channel;
    _channel = null;
    _daqmx = null;
    _utilities = null;
    if (ch != null) {
      DaqLoggers.grpc.fine('closing channel to $host:$port');
      await ch.shutdown();
    }
  }
}
