// The remote [DaqmxApi] backend: a pure-Dart gRPC client for the **NI gRPC Device
// Server** (https://github.com/ni/grpc-device, MIT-licensed). The server runs on a
// Windows/Linux host that has NI-DAQmx + the hardware; any platform — crucially
// macOS, which has no local NI-DAQmx — drives that hardware over gRPC.
//
// Same [DaqmxApi] as the FFI backend: callers can't tell local from remote. The wire
// types are generated by `package:protobuf` / `package:grpc` from the vendored protos
// (proto/, regenerate with tool/gen_proto.sh); this file only orchestrates them into
// the portable API, following the server's session model:
//   CreateTask -> Create{AI,AO}VoltageChan -> Read/WriteAnalogScalarF64 -> ClearTask.

import 'dart:typed_data';

import 'package:grpc/grpc.dart';

import 'daqmx_api.dart';
import 'daqmx_constants.dart';
import 'generated/nidaqmx.pb.dart' as pb;
import 'generated/nidaqmx.pbgrpc.dart' show NiDAQmxClient;
import 'generated/session.pb.dart' as sess;
import 'generated/session.pbgrpc.dart' show SessionUtilitiesClient;
import 'logging.dart';
import 'streaming.dart';

/// [DaqmxApi] over the NI gRPC Device Server. Construct via `Daqmx.remote(...)`.
class GrpcDaqmxBackend implements DaqmxApi {
  GrpcDaqmxBackend({
    required this.host,
    this.port = defaultPort,
    this.secure = false,
    this.credentials,
    this.callTimeout = const Duration(seconds: 30),
  });

  /// Wrap a caller-supplied [ClientChannel] (e.g. one with custom credentials,
  /// interceptors, or pointed at an in-process test server). [host]/[port] are kept
  /// only for diagnostics; the channel is used as-is. [close] still shuts it down.
  GrpcDaqmxBackend.fromChannel(
    ClientChannel channel, {
    this.host = '(injected)',
    this.port = defaultPort,
    this.callTimeout = const Duration(seconds: 30),
  })  : secure = false,
        credentials = null,
        _channel = channel;

  /// NI gRPC Device Server's default listen port.
  static const int defaultPort = 31763;

  /// Host running the NI gRPC Device Server (the box with NI-DAQmx + hardware).
  final String host;

  /// Server port (defaults to [defaultPort]).
  final int port;

  /// Whether to use TLS when [credentials] is not supplied. `secure: true` uses
  /// `ChannelCredentials.secure()` (system root CAs only) — for self-signed / private
  /// CA / mTLS deployments (typical for NI servers), pass [credentials] instead.
  final bool secure;

  /// Explicit channel credentials. When non-null this wins over [secure] and is the
  /// way to supply a custom CA, client certificate (mTLS), or authority override.
  final ChannelCredentials? credentials;

  /// Per-RPC transport deadline. Bounds *every* call so a hung or half-open server
  /// surfaces as [DaqmxUnavailable] instead of hanging the caller forever. This is the
  /// gRPC transport deadline, distinct from the DAQmx per-read/write `timeout`.
  final Duration callTimeout;

  ClientChannel? _channel;
  NiDAQmxClient? _daqmx;
  SessionUtilitiesClient? _utilities;
  bool _closed = false;
  int _warnedInsecure = 0;

  ClientChannel get _chan => _channel ??= () {
        final creds = credentials ??
            (secure ? const ChannelCredentials.secure() : const ChannelCredentials.insecure());
        if (credentials == null && !secure && _warnedInsecure++ == 0) {
          DaqLoggers.grpc.warning(
              'connecting to $host:$port over an INSECURE (cleartext) channel; '
              'anyone on-path can read or inject DAQ commands. Use secure: true or '
              'pass credentials for anything beyond a trusted, isolated network.');
        }
        DaqLoggers.grpc.fine('opening channel to $host:$port');
        return ClientChannel(host, port: port, options: ChannelOptions(credentials: creds));
      }();

  NiDAQmxClient get _ni => _daqmx ??= NiDAQmxClient(_chan);
  SessionUtilitiesClient get _util => _utilities ??= SessionUtilitiesClient(_chan);

  CallOptions get _opts => CallOptions(timeout: callTimeout);

  void _ensureOpen() {
    if (_closed) throw StateError('GrpcDaqmxBackend used after close().');
  }

  /// Translate a transport-level gRPC failure (unreachable, hung past [callTimeout],
  /// errored) into [DaqmxUnavailable] so callers handle it like the FFI "no runtime"
  /// case. DAQmx-status failures ([DaqmxException]) pass straight through.
  Future<T> _transport<T>(String op, Future<T> Function() body) async {
    _ensureOpen();
    try {
      return await body();
    } on GrpcError catch (e) {
      DaqLoggers.grpc.warning('$op transport error: ${e.codeName} ${e.message}');
      throw DaqmxUnavailable(
          'NI gRPC Device Server at $host:$port failed $op: ${e.codeName} ${e.message ?? ''}');
    }
  }

  /// Throw [DaqmxException] (enriched with the server's error string) when a DAQmx
  /// call comes back with a negative status; log positive warnings and pass through.
  Future<int> _check(int status, String op) async {
    if (status > 0) {
      DaqLoggers.grpc.warning('$op -> warning status $status');
      return status;
    }
    if (status == 0) return 0;
    String text;
    try {
      final r = await _ni.getErrorString(pb.GetErrorStringRequest(errorCode: status), options: _opts);
      text = r.errorString.isEmpty ? 'DAQmx status $status' : _clip(r.errorString);
    } on GrpcError {
      text = 'DAQmx status $status (error text unavailable)';
    }
    DaqLoggers.grpc.warning('$op -> status $status: $text');
    throw DaqmxException(status, text, operation: op);
  }

  /// Cap untrusted server-supplied error text so a hostile/buggy server can't flood
  /// logs or exception messages.
  static String _clip(String s) => s.length <= 1024 ? s : '${s.substring(0, 1024)}…';

  @override
  Future<List<String>> deviceNames() => _transport('EnumerateDevices', () async {
        final resp = await _util.enumerateDevices(sess.EnumerateDevicesRequest(), options: _opts);
        final names = resp.devices.map((d) => d.name).where((n) => n.isNotEmpty).toList();
        DaqLoggers.grpc.fine('EnumerateDevices -> $names');
        return names;
      });

  @override
  Future<double> readVoltage(
    String physicalChannel, {
    double min = -10,
    double max = 10,
    int terminalConfig = DaqmxVal.cfgDefault,
    double timeout = 10,
  }) =>
      _transport('readVoltage', () async {
        final task = await _createTask();
        try {
          await _check(
            (await _ni.createAIVoltageChan(
                    pb.CreateAIVoltageChanRequest(
                      task: task,
                      physicalChannel: physicalChannel,
                      terminalConfigRaw: terminalConfig,
                      minVal: min,
                      maxVal: max,
                      unitsRaw: DaqmxVal.volts,
                    ),
                    options: _opts))
                .status,
            'DAQmxCreateAIVoltageChan',
          );
          final r = await _ni.readAnalogScalarF64(
              pb.ReadAnalogScalarF64Request(task: task, timeout: timeout),
              options: _opts);
          await _check(r.status, 'DAQmxReadAnalogScalarF64');
          DaqLoggers.io.fine('readVoltage($physicalChannel) -> ${r.value}');
          return r.value;
        } finally {
          await _clearTask(task);
        }
      });

  @override
  Future<void> writeVoltage(
    String physicalChannel,
    double volts, {
    double min = -10,
    double max = 10,
    double timeout = 10,
  }) =>
      _transport('writeVoltage', () async {
        final task = await _createTask();
        try {
          await _check(
            (await _ni.createAOVoltageChan(
                    pb.CreateAOVoltageChanRequest(
                      task: task,
                      physicalChannel: physicalChannel,
                      minVal: min,
                      maxVal: max,
                      unitsRaw: DaqmxVal.volts,
                    ),
                    options: _opts))
                .status,
            'DAQmxCreateAOVoltageChan',
          );
          await _check(
            (await _ni.writeAnalogScalarF64(
                    pb.WriteAnalogScalarF64Request(
                      task: task,
                      autoStart: true,
                      timeout: timeout,
                      value: volts,
                    ),
                    options: _opts))
                .status,
            'DAQmxWriteAnalogScalarF64',
          );
          DaqLoggers.io.fine('writeVoltage($physicalChannel, $volts)');
        } finally {
          await _clearTask(task);
        }
      });

  /// Best-effort: the NI gRPC service exposes no `GetExtendedErrorInfo` RPC and no
  /// per-connection "last error" channel, so — unlike the FFI backend — this cannot
  /// report the most recent failure after the fact. Error text is delivered inline on
  /// each [DaqmxException] instead (via GetErrorString). Returns '' when healthy.
  @override
  Future<String> errorInfo() => _transport('GetErrorString', () async {
        final r = await _ni.getErrorString(pb.GetErrorStringRequest(errorCode: 0), options: _opts);
        return r.errorString;
      });

  @override
  Stream<TypedData> readStream(
    String physicalChannel, {
    required double rateHz,
    int samplesPerChunk = 1000,
    int? totalSamples,
    DaqSampleFormat format = DaqSampleFormat.volts,
    double min = -10,
    double max = 10,
    int terminalConfig = DaqmxVal.cfgDefault,
  }) {
    // Buffered streaming over gRPC is not wired yet. Doing it well means NI's
    // data-moniker path (DataMoniker.StreamReadWrite / BeginSidebandStream) to avoid
    // per-call protobuf+HTTP/2 overhead at sample rate — not yet vendored. For now,
    // high-rate streaming is the local FFI/native path (Daqmx.local()).
    throw UnsupportedError(
      'GrpcDaqmxBackend.readStream is not implemented. High-speed streaming uses the '
      'local FFI backend (Daqmx.local()); remote gRPC streaming needs NI\'s data-'
      'moniker/sideband RPCs (see README "Streaming"). Use scalar readVoltage over gRPC '
      'for low-rate remote sampling.',
    );
  }

  /// Create a task with an empty session name so the server assigns a unique one —
  /// no client-side name collisions even under concurrency.
  Future<sess.Session> _createTask() async {
    final r = await _ni.createTask(pb.CreateTaskRequest(sessionName: ''), options: _opts);
    await _check(r.status, 'DAQmxCreateTask');
    DaqLoggers.task.fine('CreateTask -> "${r.task.name}"');
    return r.task;
  }

  Future<void> _clearTask(sess.Session task) async {
    try {
      final r = await _ni.clearTask(pb.ClearTaskRequest(task: task), options: _opts);
      if (r.status < 0) {
        DaqLoggers.task.warning('ClearTask("${task.name}") -> status ${r.status}');
      } else {
        DaqLoggers.task.fine('ClearTask("${task.name}")');
      }
    } on GrpcError catch (e) {
      // Best-effort cleanup: a clear failure must not mask the original outcome.
      DaqLoggers.task.warning('ClearTask("${task.name}") failed: ${e.codeName}');
    }
  }

  @override
  Future<void> close() async {
    _closed = true;
    final ch = _channel;
    _channel = null;
    _daqmx = null;
    _utilities = null;
    if (ch != null) {
      DaqLoggers.grpc.fine('closing channel to $host:$port');
      await ch.shutdown();
    }
  }
}
