/// Review state of the bundled primitive icon assets (assets/prim_icons/).
///
/// Every extracted identity gets an entry — extraction NEVER silently drops
/// or hides an id; one that produced no usable asset still appears in
/// `assets/prim_icons/MANIFEST.md` with the reason. Statuses are the
/// maintainer's incremental verdicts:
///
/// - [PrimIconStatus.verified] — eyeballed against a VI render; stamped.
/// - [PrimIconStatus.unverified] — extracted but not yet reviewed; stamped
///   (that is how it gets reviewed in context) and labelled in the detail
///   card.
/// - [PrimIconStatus.rejected] — reviewed and wrong; never stamped (the node
///   falls back to the plate + operator glyph) until a better extraction or
///   a hand-drawn replacement lands.
///
/// The generator (`test/extract_prim_icons_test.dart`) rewrites the entry
/// list when assets regenerate but PRESERVES the statuses recorded here;
/// only new keys default to [PrimIconStatus.unverified].
enum PrimIconStatus { verified, unverified, rejected }

// GENERATED-ENTRIES-BEGIN (extract_prim_icons_test.dart rewrites this block;
// statuses are preserved — edit them freely.)
const Map<String, PrimIconStatus> kPrimIconStatus = {
  'class108': PrimIconStatus.unverified,
  'class147': PrimIconStatus.unverified,
  'class370': PrimIconStatus.unverified,
  'class52': PrimIconStatus.unverified,
  'class58': PrimIconStatus.verified,
  'class62': PrimIconStatus.unverified,
  'class68': PrimIconStatus.unverified,
  'prim1050': PrimIconStatus.unverified,
  'prim1051': PrimIconStatus.unverified,
  'prim1052': PrimIconStatus.unverified,
  'prim1056': PrimIconStatus.unverified,
  'prim1057': PrimIconStatus.unverified,
  'prim1058': PrimIconStatus.unverified,
  'prim1061': PrimIconStatus.unverified,
  'prim1062': PrimIconStatus.unverified,
  'prim1063': PrimIconStatus.unverified,
  'prim1064': PrimIconStatus.unverified,
  'prim1069': PrimIconStatus.unverified,
  'prim1070': PrimIconStatus.unverified,
  'prim1077': PrimIconStatus.unverified,
  'prim1078': PrimIconStatus.unverified,
  'prim1081': PrimIconStatus.unverified,
  'prim1082': PrimIconStatus.unverified,
  'prim1102': PrimIconStatus.unverified,
  'prim1103': PrimIconStatus.unverified,
  'prim1105': PrimIconStatus.unverified,
  'prim1108': PrimIconStatus.unverified,
  'prim1110': PrimIconStatus.unverified,
  'prim1112': PrimIconStatus.unverified,
  'prim1113': PrimIconStatus.unverified,
  'prim1114': PrimIconStatus.unverified,
  'prim1116': PrimIconStatus.unverified,
  'prim1118': PrimIconStatus.unverified,
  'prim1120': PrimIconStatus.unverified,
  'prim1124': PrimIconStatus.unverified,
  'prim1127': PrimIconStatus.unverified,
  'prim1128': PrimIconStatus.unverified,
  'prim1141': PrimIconStatus.unverified,
  'prim1142': PrimIconStatus.unverified,
  'prim1143': PrimIconStatus.unverified,
  'prim1145': PrimIconStatus.unverified,
  'prim1147': PrimIconStatus.unverified,
  'prim1155': PrimIconStatus.unverified,
  'prim1156': PrimIconStatus.unverified,
  'prim1162': PrimIconStatus.unverified,
  'prim1163': PrimIconStatus.unverified,
  'prim1164': PrimIconStatus.unverified,
  'prim1166': PrimIconStatus.unverified,
  'prim1167': PrimIconStatus.unverified,
  'prim1170': PrimIconStatus.unverified,
  'prim1171': PrimIconStatus.unverified,
  'prim1180': PrimIconStatus.unverified,
  'prim1181': PrimIconStatus.unverified,
  'prim1184': PrimIconStatus.unverified,
  'prim1185': PrimIconStatus.unverified,
  'prim1188': PrimIconStatus.unverified,
  'prim1189': PrimIconStatus.unverified,
  'prim1213': PrimIconStatus.verified,
  'prim1302': PrimIconStatus.unverified,
  'prim1303': PrimIconStatus.unverified,
  'prim1419': PrimIconStatus.unverified,
  'prim1420': PrimIconStatus.unverified,
  'prim1421': PrimIconStatus.unverified,
  'prim1435': PrimIconStatus.verified,
  'prim1502': PrimIconStatus.unverified,
  'prim1503': PrimIconStatus.unverified,
  'prim1516': PrimIconStatus.unverified,
  'prim1534': PrimIconStatus.verified,
  'prim1535': PrimIconStatus.verified,
  'prim1537': PrimIconStatus.unverified,
  'prim1539': PrimIconStatus.unverified,
  'prim1606': PrimIconStatus.unverified,
  'prim1608': PrimIconStatus.unverified,
  'prim1609': PrimIconStatus.unverified,
  'prim1809': PrimIconStatus.unverified,
  'prim1814': PrimIconStatus.unverified,
  'prim1815': PrimIconStatus.unverified,
  'prim1900': PrimIconStatus.unverified,
  'prim1901': PrimIconStatus.unverified,
  'prim1904': PrimIconStatus.unverified,
  'prim1907': PrimIconStatus.unverified,
  'prim1908': PrimIconStatus.unverified,
  'prim1922': PrimIconStatus.unverified,
  'prim1925': PrimIconStatus.unverified,
  'prim1926': PrimIconStatus.unverified,
  'prim1927': PrimIconStatus.unverified,
  'prim2073': PrimIconStatus.unverified,
  'prim2074': PrimIconStatus.unverified,
  'prim2075': PrimIconStatus.unverified,
  'prim2076': PrimIconStatus.unverified,
  'prim2302': PrimIconStatus.unverified,
  'prim23063': PrimIconStatus.unverified,
  'prim2308': PrimIconStatus.unverified,
  'prim2452': PrimIconStatus.unverified,
  'prim2457': PrimIconStatus.unverified,
  'prim2458': PrimIconStatus.unverified,
  'prim3914': PrimIconStatus.unverified,
  'prim8003': PrimIconStatus.unverified,
  'prim8010': PrimIconStatus.unverified,
  'prim8011': PrimIconStatus.unverified,
  'prim8018': PrimIconStatus.unverified,
  'prim8050': PrimIconStatus.unverified,
  'prim8051': PrimIconStatus.unverified,
  'prim8052': PrimIconStatus.unverified,
  'prim8055': PrimIconStatus.unverified,
  'prim8056': PrimIconStatus.unverified,
  'prim8063': PrimIconStatus.unverified,
  'prim8065': PrimIconStatus.unverified,
  'prim8070': PrimIconStatus.unverified,
  'prim8073': PrimIconStatus.unverified,
  'prim8076': PrimIconStatus.unverified,
  'prim8082': PrimIconStatus.unverified,
  'prim8083': PrimIconStatus.unverified,
  'prim8101': PrimIconStatus.unverified,
  'prim8203': PrimIconStatus.unverified,
  'prim8204': PrimIconStatus.unverified,
  'prim8205': PrimIconStatus.unverified,
};
// GENERATED-ENTRIES-END
