// Regenerates lib/src/prim_terminal_catalog.dart from the corpus.
//   dart run tool/gen_prim_terminal_census.dart   (from the app directory)
import 'dart:io';
import 'dart:typed_data';

import 'package:labwright_rsrc_parse/labwright_rsrc_parse.dart';

void main() {
  final root = Directory('../../packages/labwright_rsrc_parse/corpus/vi');
  if (!root.existsSync()) {
    stderr.writeln('corpus not found at ${root.path}');
    exit(1);
  }
  final xObs = <(int, int, int, int), Map<int, int>>{};
  final yObs = <(int, int, int, int), Map<int, int>>{};
  var files = 0, slackWires = 0;
  for (final f in root.listSync(recursive: true).whereType<File>()) {
    final path = f.path;
    final isVi =
        path.endsWith('.vi') ||
        path.endsWith('.vim') ||
        path.endsWith('.vit') ||
        path.endsWith('.ctl');
    final isPng = path.endsWith('.png');
    if (!isVi && !isPng) continue;
    Uint8List bytes;
    try {
      bytes = f.readAsBytesSync();
      if (isPng) {
        final embedded = extractSnippetVi(bytes);
        if (embedded == null) continue;
        bytes = embedded;
      }
    } catch (_) {
      continue;
    }
    ViModel model;
    try {
      model = buildViModel(bytes);
    } catch (_) {
      continue;
    }
    files++;
    for (final diagram in model.blockDiagrams) {
      for (final wire in diagram.wires) {
        final slack = wire.routeHeadSlack;
        final points = wire.routePoints;
        if (slack == null || points == null || points.isEmpty) continue;
        ViHeapObject? endpoint;
        for (final oid in wire.endpointOids) {
          final o = diagram.byId[oid];
          if (o != null && o.kind == 0x15 && o.absBounds == null) {
            endpoint = o;
            break;
          }
        }
        final dco = endpoint;
        if (dco == null) continue;
        final node = diagram.byId[dco.parentOid];
        final box = node?.absBounds;
        if (node == null || box == null || box.width <= 0 || box.height <= 0) {
          continue;
        }
        final dcos = [
          for (final c in diagram.children(node.oid))
            if (c.kind == 0x15) c,
        ];
        final termIdx = dcos.indexWhere((c) => c.oid == dco.oid);
        if (termIdx < 0) continue;
        final key = (
          node.primResId ?? -node.kind,
          termIdx,
          box.width,
          box.height,
        );
        final head = points.first;
        slackWires++;
        if (slack.dx != 0) {
          (yObs[key] ??= {}).update(
            head.y - box.top,
            (c) => c + 1,
            ifAbsent: () => 1,
          );
        } else {
          (xObs[key] ??= {}).update(
            head.x - box.left,
            (c) => c + 1,
            ifAbsent: () => 1,
          );
        }
      }
    }
  }
  stderr.writeln(
    'files=$files slackWires=$slackWires keys=${{...xObs.keys, ...yObs.keys}.length}',
  );

  final keys = {...xObs.keys, ...yObs.keys}.toList()
    ..sort((a, b) {
      var c = a.$1.compareTo(b.$1);
      if (c != 0) return c;
      c = a.$2.compareTo(b.$2);
      if (c != 0) return c;
      c = a.$3.compareTo(b.$3);
      return c != 0 ? c : a.$4.compareTo(b.$4);
    });
  final out = StringBuffer('''
// GENERATED by the corpus prim-terminal census — do not hand-edit.
// Regenerate: dart run tool/gen_prim_terminal_census.dart (app directory).

const Map<(int, int, int, int), ({int? dx, int? dy})> kBdPrimTerminalCensus = {
''');
  var shipped = 0, axisConflicts = 0;
  for (final key in keys) {
    ({int offset, int count})? unanimous(Map<int, int>? obs) {
      if (obs == null || obs.isEmpty) return null;
      if (obs.length > 1) {
        axisConflicts++;
        return null;
      }
      return (offset: obs.keys.single, count: obs.values.single);
    }

    final x = unanimous(xObs[key]);
    final y = unanimous(yObs[key]);
    if (x == null && y == null) continue;
    shipped++;
    out.writeln(
      '  (${key.$1}, ${key.$2}, ${key.$3}, ${key.$4}): '
      '(dx: ${x?.offset}, dy: ${y?.offset}), '
      '// x${x?.count ?? 0} y${y?.count ?? 0}',
    );
  }
  out.writeln('};');
  stderr.writeln('entries=$shipped axisConflictsDropped=$axisConflicts');
  File('lib/src/prim_terminal_catalog.dart').writeAsStringSync(out.toString());
  stderr.writeln('wrote lib/src/prim_terminal_catalog.dart');
}
