// Regenerates lib/src/prim_terminal_catalog.dart from the corpus.
//
// Derivation (pure file geometry, no reference pixels): every bent reverse
// walk ships with `ViWire.routeHeadSlack`, and its walk pins the route
// origin's coordinate PERPENDICULAR to the slack axis exactly (the stored
// segment lengths are exact and the anchored tail is a decoded attach
// point). Sweeping every slack wire in the corpus and grouping by prim key
// therefore assembles terminal positions axis by axis; an axis ships only
// when every observation agrees (per-axis conflicts are dropped).
//
//   dart run tool/gen_prim_terminal_census.dart   (from the app directory)
import 'dart:io';
import 'dart:typed_data';

import 'package:labwright_rsrc_parse/labwright_rsrc_parse.dart';

void main() {
  final root = Directory('../../packages/labwright_rsrc_parse/corpus/vi');
  if (!root.existsSync()) {
    stderr.writeln('corpus not found at ${root.path}');
    exit(1);
  }
  // Per (iconKey, termIdx, boxW, boxH) per axis: observed offset → count.
  final xObs = <(int, int, int, int), Map<int, int>>{};
  final yObs = <(int, int, int, int), Map<int, int>>{};
  var files = 0, slackWires = 0;
  for (final f in root.listSync(recursive: true).whereType<File>()) {
    final path = f.path;
    final isVi =
        path.endsWith('.vi') ||
        path.endsWith('.vim') ||
        path.endsWith('.vit') ||
        path.endsWith('.ctl');
    final isPng = path.endsWith('.png');
    if (!isVi && !isPng) continue;
    Uint8List bytes;
    try {
      bytes = f.readAsBytesSync();
      if (isPng) {
        final embedded = extractSnippetVi(bytes);
        if (embedded == null) continue;
        bytes = embedded;
      }
    } catch (_) {
      continue;
    }
    ViModel model;
    try {
      model = buildViModel(bytes);
    } catch (_) {
      continue;
    }
    files++;
    for (final diagram in model.blockDiagrams) {
      for (final wire in diagram.wires) {
        final slack = wire.routeHeadSlack;
        final points = wire.routePoints;
        if (slack == null || points == null || points.isEmpty) continue;
        // The head (prim-terminal end) is the FIRST route point; the anchor
        // is the explicit trailing point. The head endpoint is the one whose
        // terminal is a bare 0x15 DCO under the prim node.
        ViHeapObject? dco;
        for (final oid in wire.endpointOids) {
          final o = diagram.byId[oid];
          if (o != null && o.kind == 0x15 && o.absBounds == null) {
            dco = o;
            break;
          }
        }
        if (dco == null) continue;
        final node = diagram.byId[dco.parentOid ?? -1];
        final box = node?.absBounds;
        if (node == null || box == null || box.width <= 0 || box.height <= 0) {
          continue;
        }
        final dcos = [
          for (final c in diagram.children(node.oid))
            if (c.kind == 0x15) c,
        ];
        final termIdx = dcos.indexWhere((c) => c.oid == dco!.oid);
        if (termIdx < 0) continue;
        final key = (
          node.primResId ?? -node.kind,
          termIdx,
          box.width,
          box.height,
        );
        final head = points.first;
        slackWires++;
        if (slack.dx != 0) {
          // Slack along x: the head's Y is exact.
          (yObs[key] ??= {}).update(
            head.y - box.top,
            (c) => c + 1,
            ifAbsent: () => 1,
          );
        } else {
          (xObs[key] ??= {}).update(
            head.x - box.left,
            (c) => c + 1,
            ifAbsent: () => 1,
          );
        }
      }
    }
  }
  stderr.writeln(
    'files=$files slackWires=$slackWires keys=${{...xObs.keys, ...yObs.keys}.length}',
  );

  final keys = {...xObs.keys, ...yObs.keys}.toList()
    ..sort((a, b) {
      var c = a.$1.compareTo(b.$1);
      if (c != 0) return c;
      c = a.$2.compareTo(b.$2);
      if (c != 0) return c;
      c = a.$3.compareTo(b.$3);
      return c != 0 ? c : a.$4.compareTo(b.$4);
    });
  final out = StringBuffer('''
// GENERATED by the corpus prim-terminal census — do not hand-edit.
// Regenerate: dart run tool/gen_prim_terminal_census.dart (app directory).

/// Corpus-pinned builtin prim terminal offsets, keyed like
/// `_kBdPrimTerminals` in diagram_view.dart: (icon key — primResID or
/// negated class code, terminal index among the prim's `0x15` DCO
/// children, box width, box height) → offsets from the box top-left, an
/// axis null while unpinned.
///
/// Derivation (pure file geometry, no reference pixels): every bent
/// reverse walk ships with `ViWire.routeHeadSlack`, and its walk pins the
/// route origin's coordinate PERPENDICULAR to the slack axis exactly (the
/// stored segment lengths are exact and the anchored tail is a decoded
/// attach point). Sweeping every slack wire in the corpus and grouping by
/// prim key therefore assembles terminal positions axis by axis; an axis
/// ships only when every observation agrees (per-axis conflicts are
/// dropped). The trailing comment on each entry counts the x / y
/// observations behind it.
const Map<(int, int, int, int), ({int? dx, int? dy})> kBdPrimTerminalCensus = {
''');
  var shipped = 0, axisConflicts = 0;
  for (final key in keys) {
    int? unanimous(Map<int, int>? obs) {
      if (obs == null || obs.isEmpty) return null;
      if (obs.length > 1) {
        axisConflicts++;
        return null;
      }
      return obs.keys.single;
    }

    final xs = xObs[key], ys = yObs[key];
    final dx = unanimous(xs);
    final dy = unanimous(ys);
    if (dx == null && dy == null) continue;
    shipped++;
    final xCount = dx == null ? 0 : xs!.values.single;
    final yCount = dy == null ? 0 : ys!.values.single;
    out.writeln(
      '  (${key.$1}, ${key.$2}, ${key.$3}, ${key.$4}): '
      '(dx: $dx, dy: $dy), // x$xCount y$yCount',
    );
  }
  out.writeln('};');
  stderr.writeln('entries=$shipped axisConflictsDropped=$axisConflicts');
  File('lib/src/prim_terminal_catalog.dart').writeAsStringSync(out.toString());
  stderr.writeln('wrote lib/src/prim_terminal_catalog.dart');
}
