name: labwright_rsrc_parse
description: Clean-room RSRC parser and decoder
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0

executables:
  vi-inspect: inspect

dependencies:
  archive: ^4.0.9

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
  crypto: ^3.0.7
